version: "3"
services:
  db:
    image: postgres:latest
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 010505
      POSTGRES_DB: review_product_tokopedia
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
